---
- name: Create directories for iRedMail
  file:
    path: "/srv/iredmail/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
  with_items:
    - mail
    - clamav
    - dbdata

- name: Create Docker Compose file for iRedMail
  copy:
    dest: /srv/iredmail/docker-compose.yml
    content: |
      version: '3.8'

      services:
        mailserver:
          image: onlyoffice/mailserver
          container_name: iredmail_server
          ports:
            - 25:25
            - 143:143
            - 587:587
            - 993:993
          environment:
            - DB_TYPE=mysql
            - DB_HOST=db
            - DB_NAME={{ iredmail_db_name }}
            - DB_USER={{ iredmail_db_user }}
            - DB_PASSWD={{ iredmail_db_password }}
            - RSPAMD_PASSWORD={{ iredmail_rspamd_password }}
            - MYSQL_ROOT_PASSWORD={{ iredmail_root_password }}
            - DOMAIN={{ iredmail_domain }}
            - HOSTNAME={{ iredmail_hostname }}
          volumes:
            - /srv/iredmail/mail:/var/vmail
            - /srv/iredmail/clamav:/var/lib/clamav
          restart: always

        db:
          image: mariadb
          container_name: iredmail_db
          environment:
            MYSQL_ROOT_PASSWORD: {{ iredmail_root_password }}
            MYSQL_DATABASE: {{ iredmail_db_name }}
            MYSQL_USER: {{ iredmail_db_user }}
            MYSQL_PASSWORD: {{ iredmail_db_password }}
          volumes:
            - /srv/iredmail/dbdata:/var/lib/mysql
          restart: always

- name: Start iRedMail using Docker Compose
  shell: |
    docker compose up -d
  args:
    chdir: /srv/iredmail
