---
- name: Create directories for Vaultwarden
  file:
    path: "/srv/vaultwarden/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
  with_items:
    - data
    - ssl

- name: Create Docker Compose file for Vaultwarden
  copy:
    dest: /srv/vaultwarden/docker-compose.yml
    content: |
      version: '3.8'
      services:
        vaultwarden:
          image: vaultwarden/server
          container_name: vaultwarden_server
          ports:
            - "{{ item.port }}:80"  # Dynamically use the port from subdomains.yml
          environment:
            - ADMIN_TOKEN={{ admin_token }}
            - VIRTUAL_HOST={{ item.subdomain }}.{{ cloudflare_domain }}  # Use the subdomain from subdomains.yml
            - VIRTUAL_PORT=80  # Fixed internal port for Vaultwarden
            - LETSENCRYPT_HOST={{ item.subdomain }}.{{ cloudflare_domain }}  # Let’s Encrypt certificate for the subdomain
            - LETSENCRYPT_EMAIL={{ certbot_email }}
          volumes:
            - /srv/vaultwarden/data:/data
            - /srv/vaultwarden/ssl:/ssl
          networks:
            - app-suite
          restart: always

      networks:
        app-suite:
          driver: bridge
          external: true
  loop: "{{ subdomains }}"
  when: item.service == "vaultwarden"

  vars:
    admin_token: your_admin_token

- name: Start Vaultwarden using Docker Compose
  shell: |
    docker compose up -d
  args:
    chdir: /srv/vaultwarden
