---
- name: Create directories for Mattermost
  file:
    path: "/srv/mattermost/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
  with_items:
    - config
    - data
    - logs

- name: Create directories for Mattermost database
  file:
    path: "/srv/mattermost/dbdata"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"

- name: Create Docker Compose file for Mattermost
  copy:
    dest: /srv/mattermost/docker-compose.yml
    content: |
      services:
        db:
          container_name: mattermost-db
          image: postgres:13
          restart: always
          volumes:
            - /srv/mattermost/dbdata:/var/lib/postgresql/data
          environment:
            POSTGRES_USER: {{ mattermost_db_user }}
            POSTGRES_PASSWORD: {{ mattermost_db_password }}
            POSTGRES_DB: {{ mattermost_db_name }}

        app:
          container_name: mattermost-app
          image: mattermost/mattermost-team-edition:latest
          restart: always
          depends_on:
            - db
          ports:
            - "8083:8065"
          volumes:
            - /srv/mattermost/data:/mattermost/data
          environment:
            MM_SQLSETTINGS_DRIVERNAME: postgres
            MM_SQLSETTINGS_DATASOURCE: postgres://{{ mattermost_db_user }}:{{ mattermost_db_password }}@db:5432/{{ mattermost_db_name }}?sslmode=disable
            MM_SERVICESETTINGS_SITEURL: http://localhost:8065

- name: Start Mattermost using Docker Compose
  shell: |
    docker compose up -d
  args:
    chdir: /srv/mattermost
