
---
- name: Create directories for GitLab
  file:
    path: "/srv/gitlab/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - config
    - data
    - logs

- name: Create Docker Compose file for GitLab
  copy:
    dest: /srv/gitlab/docker-compose.yml
    content: |
      version: '3'
      services:
        gitlab:
          image: 'gitlab/gitlab-ce:latest'
          container_name: 'gitlab'
          restart: always
          hostname: 'gitlab.example.com'
          environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://gitlab.example.com'
          ports:
            - '80:80'
            - '443:443'
            - '22:22'
          volumes:
            - '/srv/gitlab/config:/etc/gitlab'
            - '/srv/gitlab/logs:/var/log/gitlab'
            - '/srv/gitlab/data:/var/opt/gitlab'

- name: Start GitLab using Docker Compose
  shell: |
    docker-compose up -d
  args:
    chdir: /srv/gitlab
