---
- name: Create directories for Nextcloud
  file:
    path: "/srv/nextcloud/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
  with_items:
    - app
    - data
    - dbdata

- name: Create Docker Compose file for Nextcloud
  copy:
    dest: /srv/nextcloud/docker-compose.yml
    content: |
      version: '3.8'
      services:
        nextcloud_db:
          image: mariadb
          container_name: nextcloud_db
          restart: always
          volumes:
            - /srv/nextcloud/dbdata:/var/lib/mysql
          environment:
            MYSQL_ROOT_PASSWORD: {{ nextcloud_db_root_password }}
            MYSQL_DATABASE: {{ nextcloud_db_name }}
            MYSQL_USER: {{ nextcloud_db_user }}
            MYSQL_PASSWORD: {{ nextcloud_db_password }}
          networks:
            - app-suite

        app:
          image: nextcloud
          container_name: nextcloud_app
          restart: always
          ports:
            - "{{ item.port }}:80"  # Dynamically expose the port from subdomains.yml
          depends_on:
            - nextcloud_db
          volumes:
            - /srv/nextcloud/app:/var/www/html
          environment:
            - MYSQL_PASSWORD={{ nextcloud_db_password }}
            - MYSQL_DATABASE={{ nextcloud_db_name }}
            - MYSQL_USER={{ nextcloud_db_user }}
            - MYSQL_HOST=nextcloud_db
            - VIRTUAL_HOST={{ item.subdomain }}.{{ cloudflare_domain }}  # Set the subdomain for NGINX proxy
            - VIRTUAL_PORT=80  # Port inside the Nextcloud container
            - LETSENCRYPT_HOST={{ item.subdomain }}.{{ cloudflare_domain }}  # Request a certificate for this subdomain
            - LETSENCRYPT_EMAIL={{ certbot_email }}
          networks:
            - app-suite
      networks:
        app-suite:
          driver: bridge
          external: true
  with_items: "{{ subdomains }}"
  when: item.service == "nextcloud"

- name: Start Nextcloud using Docker Compose
  shell: |
    docker compose up -d
  args:
    chdir: /srv/nextcloud
