
---
- name: Create directories for Nextcloud
  file:
    path: "/srv/nextcloud/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - app
    - data

- name: Create Docker Compose file for Nextcloud
  copy:
    dest: /srv/nextcloud/docker-compose.yml
    content: |
      version: '3'
      services:
        nextcloud:
          image: nextcloud
          restart: unless-stopped
          ports:
            - "8080:80"
          volumes:
            - /srv/nextcloud/app:/var/www/html
            - /srv/nextcloud/data:/var/www/html/data

- name: Start Nextcloud using Docker Compose
  shell: |
    docker-compose up -d
  args:
    chdir: /srv/nextcloud
